# Coolify configuration
# Deploy pre-built static files instead of building from source

version: "3.8"

services:
  web:
    image: nginx:alpine
    volumes:
      - ./out:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped
